# Generated by Django 3.2.5 on 2021-09-06 04:03

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_buyer', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('is_DeliveryMan', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryManModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('bio', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=255)),
                ('facebook', models.CharField(default='', max_length=255)),
                ('documentID', models.CharField(default='', max_length=255)),
                ('documentType', models.CharField(choices=[('Driving License', 'Driving License'), ('NID', 'NID'), ('Passport', 'Passport')], default='', max_length=255)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor.fields.RichTextField()),
                ('location', models.CharField(default='', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('website', models.CharField(default='', max_length=255)),
                ('type', models.CharField(choices=[('Book Store', 'Book Store'), ('Cosmetics House', 'Cosmetics House'), ('Drug Store', 'Drug Store'), ('Electronic Store', 'Electronic Store'), ('Food Marts', 'Food Marts'), ('Fashion House', 'Fashion House'), ('Home Appliances Store', 'Home Appliances Store'), ('Lifestyle Store', 'Lifestyle Store'), ('Mom and Kids', 'Mom and Kids'), ('Sports Hub', 'Sports Hub')], default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('availQuantity', models.IntegerField(default=0)),
                ('refill', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PreferredAreaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='', max_length=255)),
                ('time', models.CharField(choices=[('9am-3pm', '9am-3pm'), ('3pm-9pm', '3pm-9pm')], default='', max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'area')},
            },
        ),
        migrations.CreateModel(
            name='AvailabilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=1000)),
                ('phone', models.CharField(default='', max_length=255)),
                ('time', models.CharField(choices=[('9am-3pm', '9am-3pm'), ('3pm-9pm', '3pm-9pm')], default='', max_length=255)),
                ('Days', models.CharField(default='', max_length=255)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('buyer', 'address', 'Days', 'time')},
            },
        ),
    ]
