# Generated by Django 3.2.5 on 2021-09-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitymodel',
            name='Days',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='availabilitymodel',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='availabilitymodel',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='availabilitymodel',
            name='time',
            field=models.CharField(choices=[('9am-3pm', '9am-3pm'), ('3pm-9pm', '3pm-9pm')], max_length=255),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='type',
            field=models.CharField(choices=[('Book Store', 'Book Store'), ('Cosmetics House', 'Cosmetics House'), ('Drug Store', 'Drug Store'), ('Electronic Store', 'Electronic Store'), ('Food Marts', 'Food Marts'), ('Fashion House', 'Fashion House'), ('Home Appliances Store', 'Home Appliances Store'), ('Lifestyle Store', 'Lifestyle Store'), ('Mom and Kids', 'Mom and Kids'), ('Sports Hub', 'Sports Hub')], max_length=255),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliverymanmodel',
            name='documentID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverymanmodel',
            name='documentType',
            field=models.CharField(choices=[('Driving License', 'Driving License'), ('NID', 'NID'), ('Passport', 'Passport')], max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverymanmodel',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='preferredareamodel',
            name='area',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='preferredareamodel',
            name='time',
            field=models.CharField(choices=[('9am-3pm', '9am-3pm'), ('3pm-9pm', '3pm-9pm')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
