# Generated by Django 3.2.5 on 2021-07-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_productmodel_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productmodel',
            unique_together={('user', 'name')},
        ),
    ]
