# Generated by Django 3.2.5 on 2021-08-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_timeslotmodel_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslotmodel',
            unique_together={('time', 'Day')},
        ),
    ]
