# Generated by Django 3.2.5 on 2021-07-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_productmodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
