# Generated by Django 3.2.5 on 2021-08-02 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_timeslotmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitymodel',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
