# Generated by Django 3.2.5 on 2021-08-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_availabilitymodel_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressphonemodel',
            name='user',
        ),
    ]
