# Generated by Django 3.2.5 on 2021-08-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_addressphonemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitymodel',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='availabilitymodel',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='AddressPhoneModel',
        ),
    ]
