# Generated by Django 3.2.5 on 2021-08-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_availabilitymodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitymodel',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='availabilitymodel',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
