# Generated by Django 3.2.5 on 2021-08-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_availabilitymodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitymodel',
            name='Days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='availabilitymodel',
            name='time',
            field=models.CharField(blank=True, choices=[('9am-3pm', '9am-3pm'), ('3pm-9pm', '3pm-9pm')], max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='availabilitymodel',
            unique_together={('buyer', 'address', 'Days', 'time')},
        ),
        migrations.RemoveField(
            model_name='availabilitymodel',
            name='slot_id',
        ),
        migrations.DeleteModel(
            name='TimeSlotModel',
        ),
    ]
