# Generated by Django 3.2.5 on 2021-08-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210802_1258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preferredareamodel',
            unique_together={('user', 'area')},
        ),
    ]
