# Generated by Django 3.2.5 on 2021-08-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_preferredareamodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferredareamodel',
            name='time',
            field=models.CharField(blank=True, choices=[('9am-3pm', '9am-3pm'), ('3pm-9pm', '3pm-9pm')], max_length=255, null=True),
        ),
    ]
