# Generated by Django 3.2.5 on 2021-08-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_preferredareamodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='availQuantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
