# Generated by Django 3.2.5 on 2021-07-26 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_deliverymanmodel_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='ordermodel',
            unique_together={('buyer', 'product')},
        ),
    ]
