# Generated by Django 3.2.5 on 2021-08-27 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20210827_1909'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderschedulemodel',
            unique_together={('order', 'deliveryMan')},
        ),
    ]
