# Generated by Django 3.2.5 on 2021-08-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderschedulemodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderschedulemodel',
            unique_together=set(),
        ),
    ]
