# Generated by Django 3.2.5 on 2021-08-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderschedulemodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderschedulemodel',
            name='code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
