# Generated by Django 3.2.5 on 2021-08-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210827_2238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordermodel',
            unique_together=set(),
        ),
    ]
