# Generated by Django 3.2.5 on 2021-08-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210827_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderschedulemodel',
            name='postDate',
            field=models.DateTimeField(null=True),
        ),
    ]
