# Generated by Django 3.2.5 on 2021-08-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_orderschedulemodel_is_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderschedulemodel',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
